baseurl: "https://example.com"
languageCode: "en-us"
title: "â„œğ”¬ğ”Ÿğ”Ÿğ”¶"
theme: "hugo-tania"

paginate: 20

# disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: "â„œ"

  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "â„œğ”¬ğ”Ÿğ”Ÿğ”¶"
  siteDesc: ""
  author: "Robby"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    email: ""
    github: ""
    linkedin: ""
    stack-overflow: ""
    telegram: ""
    twitter: ""
  
  # Comments settings
  comments:
    enabled: false

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
