theme = "hugo-tania"

baseurl = "https://h0rv.github.io/"
title = "â„œğ”¬ğ”Ÿğ”Ÿğ”¶"
author = "Robby"

paginate = 10

[params]
  enableFootnotes = true
  [params.colorScheme]
    toggle = true
    default = "auto"

[menu]
  [[menu.header]]
    name = "About"
    url = "/about/"
  [[menu.header]]
    name = "Board"
    url = "/board/"
  [[menu.header]]
    name = "Posts"
    url = "/posts/"
  [[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
