baseurl = "https://h0rv.github.io/"
theme = "holy"
title = "â„œğ”¬ğ”Ÿğ”Ÿğ”¶"
author = "Robby"
copyright = ""

paginate = 10

languageCode = "en"
DefaultContentLanguage = "en"

enableInlineShortcodes = false

[params]
  copyright = "Â© h0rv"

[menu]

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[services]

